2024-03-09 19:55:18,427 INFO    MainThread:52903 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_setup.py:_flush():76] Configure stats pid to 52903
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_setup.py:_flush():76] Loading settings from /Users/junyangsun/.config/wandb/settings
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_setup.py:_flush():76] Loading settings from /Users/junyangsun/Documents/GitHub/NextFramePred4Pong/wandb/settings
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_just_transformer.py', 'program_abspath': '/Users/junyangsun/Documents/GitHub/NextFramePred4Pong/train_just_transformer.py', 'program': 'train_just_transformer.py'}
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_init.py:_log_setup():526] Logging user logs to /Users/junyangsun/Documents/GitHub/NextFramePred4Pong/wandb/run-20240309_195518-uk2b29op/logs/debug.log
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/junyangsun/Documents/GitHub/NextFramePred4Pong/wandb/run-20240309_195518-uk2b29op/logs/debug-internal.log
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_init.py:init():566] calling init triggers
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 200, 'batch_size': 8, 'image_size': 32, 'N_input_frames': 4, 'N_predictions': 4}
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_init.py:init():616] starting backend
2024-03-09 19:55:18,428 INFO    MainThread:52903 [wandb_init.py:init():620] setting up manager
2024-03-09 19:55:18,431 INFO    MainThread:52903 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-03-09 19:55:18,432 INFO    MainThread:52903 [wandb_init.py:init():628] backend started and connected
2024-03-09 19:55:18,449 INFO    MainThread:52903 [wandb_init.py:init():720] updated telemetry
2024-03-09 19:55:18,490 INFO    MainThread:52903 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-09 19:55:18,715 ERROR   MainThread:52903 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-09 19:55:18,914 ERROR   MainThread:52903 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/junyangsun/opt/anaconda3/envs/psych209/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/junyangsun/opt/anaconda3/envs/psych209/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-09 19:55:19,923 WARNING MsgRouterThr:52903 [router.py:message_loop():77] message_loop has been closed
